USE TSQL2012


GO 
IF OBJECT_ID('dbo.SKU','U') IS NOT NULL DROP TABLE dbo.SKU

GO
CREATE TABLE dbo.SKU
(
 ID_SKU INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
Code AS ('s'+CAST(ID_SKU AS VARCHAR(11))) UNIQUE, 
Name VARCHAR(11) NOT NULL
)


GO 
IF OBJECT_ID('dbo.Family','U') IS NOT NULL DROP TABLE dbo.Family
GO
CREATE TABLE dbo.Family
(
ID_Family INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
SurName VARCHAR(11) NOT NULL,
BudgetValue MONEY  NOT NULL
)


GO
IF OBJECT_ID('dbo.Basket','U') IS NOT NULL DROP TABLE dbo.Basket
GO
CREATE TABLE dbo.Basket 
(
ID_Basket INT IDENTITY(1,1)  NOT NULL,
ID_SKU INT NOT NULL,
CONSTRAINT FK_Basket_SKU FOREIGN KEY(ID_SKU) REFERENCES dbo.SKU(ID_SKU),
ID_Family INT NOT NULL,
CONSTRAINT FK_Basket_Family FOREIGN KEY(ID_Family) REFERENCES dbo.Family(ID_Family),
Quantity INT NOT NULL,
Value INT NOT NULL,
PurchaseDate DATE NOT NULL DEFAULT SYSDATETIME(),
DiscountValue INT NOT NULL,
CONSTRAINT Check_Quantity_Value CHECK (Value>0 AND Quantity>0)
)
