USE TSQL2012

GO
IF OBJECT_ID('dbo.udf_GetSKUPrice','fN') IS NOT NULL DROP FUNCTION dbo.udf_GetSKUPrice

GO
CREATE FUNCTION dbo.udf_GetSKUPrice(@ID_SKU INT)
RETURNS DECIMAL(18,2)
AS 
BEGIN
DECLARE @result DECIMAL(18,2)
SELECT @result=CAST(B.Value AS DECIMAL(18,2))/CAST(B.Quantity AS DECIMAL(18,2)) 
FROM dbo.Basket AS B
WHERE B.ID_SKU=@ID_SKU
RETURN @result
END;